services:
  # 1. APACHE NIFI
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTP_PORT=
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=password12345678
      - NIFI_JVM_HEAP_INIT=512m
      - NIFI_JVM_HEAP_MAX=1024m
    volumes:
      - nifi:/opt/nifi/nifi-current/logs
      - nifi:/opt/nifi/nifi-current/conf
      - nifi:/opt/nifi/nifi-current/database_repository
      - nifi:/opt/nifi/nifi-current/flowfile_repository
      - nifi:/opt/nifi/nifi-current/content_repository
      - nifi:/opt/nifi/nifi-current/provenance_repository
      - nifi:/opt/nifi/nifi-current/python_extensions
      - nifi:/opt/nifi/nifi-current/nar_extensions
      - nifi:/opt/nifi/nifi-current/state
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1536M
    networks:
      - bigdata-net

  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    ports:
      - "18080:18080"
    networks:
      - bigdata-net


  # 2. APACHE ZOOKEEPER 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - bigdata-net

  # 3. APACHE KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    networks:
      - bigdata-net
      
  # 4. APACHE SPARK (master)
  spark-master:
    image: apache/spark:3.4.2
    container_name: spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Communication Port
    environment:
      SPARK_DAEMON_MASTER: "true"
      SPARK_MASTER_PORT: "7077"
      SPARK_MASTER_WEBUI_PORT: "8080"
      SPARK_DAEMON_MEMORY: "800m"
    volumes:
      - ./src:/opt/spark/apps
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1280M
    networks:
      - bigdata-net

  # 5. APACHE SPARK (worker)
  spark-worker:
    image: apache/spark:3.4.2
    container_name: spark-worker
    depends_on:
      - spark-master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      SPARK_DAEMON_WORKER: "true"
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "1024m"
      SPARK_DAEMON_MEMORY: "512m"
      SPARK_MASTER: "spark://spark-master:7077"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1792M
    networks:
      - bigdata-net

  # 6. ELASTICSEARCH (Storage)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    networks:
      - bigdata-net

  # 7. KIBANA (Visualization)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - kibana_data:/usr/share/kibana/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge

volumes:
  nifi:
  es_data:
  kibana_data:
